### ISSUE TITLE
DermTiffImageの__init__のオプショナル引数

### ISSUE THREAD

**Issue by mikimotom** [athnomedical/derm_tiff#3]
オプショナル引数のlabel2maskとlabel2colorを指定しないと、25行目でAssertion Errorが出る。
https://github.com/athnomedical/derm_tiff/blob/511238ab33fc4bd3717b4d9c54a77f895ab08f96/derm_tiff/derm_tiff_image.py#L25

**Comment by kawa-yo** [comment]
@mikimotom 
[Test PYPI](https://test.pypi.org/project/derm-tiff/)というpythonパッケージインデックスのテスト環境に修正を加えたものをアップロードしました．

以下のスクリプトを実行してインストールし，動作の確認をお願いします．

```
pip install -i https://test.pypi.org/simple/ derm-tiff
```

**Comment by mikimotom** [comment]
@kawa-yo 
早速ご対応いただきましてありがとうございます。
問題なく動作することを確認しました。

**Comment by kawa-yo** [comment]
masterにマージし，[PYPI](https://pypi.org/project/derm-tiff/)にアップロードしました．
